-- EMERGENCY DATABASE RESET
-- This script will delete the broken table and re-create it correctly from scratch.

-- 1. DROP the existing table (This deletes current comments, but fixes the schema)
DROP TABLE IF EXISTS public.portfolio_comments;

-- 2. CREATE the table again with the CORRECT schema
create table public.portfolio_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_name text not null,
  profile_image text -- No "NOT NULL" here, ensuring it is optional
);

-- 3. ENABLE Row Level Security (RLS)
alter table public.portfolio_comments enable row level security;

-- 4. CREATE Permission Policies
create policy "Enable read access for all users"
on public.portfolio_comments
for select
using (true);

create policy "Enable insert access for all users"
on public.portfolio_comments
for insert
with check (true);
