-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)

-- 1. Create the table if it doesn't exist
create table if not exists public.portfolio_comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  user_name text not null,
  profile_image text
);

-- 2. Enable RLS
alter table public.portfolio_comments enable row level security;

-- 3. Create Policy for Reading (SELECT) - Allow everyone to see comments
create policy "Enable read access for all users"
on public.portfolio_comments
for select
using (true);

-- 4. Create Policy for Writing (INSERT) - Allow everyone to post comments
create policy "Enable insert access for all users"
on public.portfolio_comments
for insert
with check (true);

-- STORAGE POLICIES
-- NOTE: You must first create a bucket named 'profile_images' in the Storage menu

-- 5. Allow Public Read access to the bucket
create policy "Give public access to profile_images"
on storage.objects
for select
using ( bucket_id = 'profile_images' );

-- 6. Allow Public Upload access to the bucket
create policy "Allow public uploads to profile_images"
on storage.objects
for insert
with check ( bucket_id = 'profile_images' );
